### ISSUE TITLE
Build error on windows

### ISSUE THREAD

**Issue by LucaGabi** [mauron85/cordova-plugin-background-geolocation-example#12]
There is an error, not working:

C:\work\cpgps>npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! com.marianhello.bgexampleapp@2.0.0 clean: rimraf www/*!\(gitignore\)
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the com.marianhello.bgexampleapp@2.0.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Luca\AppData\Roaming\npm-cache_logs\2018-05-01T14_21_45_630Z-debug.log

**Comment by mauron85** [comment]
fixed! just update your repo. thank you for reporting

**Comment by mauron85** [comment]
and also rerun `npm install`
