### ISSUE TITLE
Is there a non-React example?

### ISSUE THREAD

**Issue by becauseinterwebs** [mauron85/cordova-plugin-background-geolocation-example#13]
I am updating a very simple app that was built using 1.x  I followed the migration guide from 1.x to 2.x and then to 3.x.

Is there an example of the 3.x that is not React based?

Thank you!

**Comment by mauron85** [comment]
This is last commit which doesn't use React
https://github.com/mauron85/cordova-plugin-background-geolocation-example/blob/4f6231ccdcd3531e80e48fa65a65037baee58b09/www/app.js

But it's using 2.x branch.

**Comment by mauron85** [comment]
So to answer your question. No there is not.
