### ISSUE TITLE
adb installation error: INSTALL_FAILED_CONFLICTING_PROVIDER

### ISSUE THREAD

**Issue by harisrnd** [mauron85/cordova-plugin-background-geolocation-example#25]
I have two apps using your plugin and they cannot be installed on the same device. The apps use the same codebase.
I believe the problem is in plugin.xml:
<provider
                android:name="com.marianhello.bgloc.data.provider.LocationContentProvider"
                android:authorities="@string/mauron85_bgloc_content_authority"
                android:exported="false"
                android:syncable="true"/>

See https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/750#issuecomment-272349681
Please advise if there is a workaround.

**Comment by harisrnd** [comment]
Sorry, I opened this here by mistake. Closing here.

**Comment by peppedeka** [comment]
hi @harisrnd  i have same problem you fix it???
