### ISSUE TITLE
background tracking not working

### ISSUE THREAD

**Issue by guestisp** [mauron85/cordova-plugin-background-geolocation-example#4]
i'm trying to use the background tracking.
I don't have any errors, but the javascript callback is not called (probably this is normale when app is in background) but also the http post request is not called.

i've configured it like this:
```
window.backgroundGeolocation.configure(
   watchPositionSuccessCallback,
   watchPositionErrorCallback,
   {
       desiredAccuracy: 0,
       interval: 10,
       activityType: 'AutomotiveNavigation',

       notificationTitle: 'My App',
       notificationText: 'My Text',

       url: api_domain+'/orders/'+order_uuid+'/route',
       httpHeaders: {
           'Authorization': sessionStorage.getItem('http_auth')
       },

       pauseLocationUpdates: false,
   }
);
$scope.startBackgroundGeolocation();
```

at least I should receive an HTTP POST on my server, but this doesn't happen.

**Comment by leohenrique** [comment]
Could you solve that?

I'm struggling with the same problem

**Comment by guestisp** [comment]
A permission is missing: https://github.com/mauron85/cordova-plugin-background-geolocation/issues/654

try to manually add that permission in Android Manifest and check
